# Generated by Django 4.2.2 on 2023-12-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug_field',
            new_name='product_slug',
        ),
    ]
