# Generated by Django 4.2.2 on 2023-12-14 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_colorvariant_sizevariant_product_color_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_code', models.CharField(max_length=20)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_amount', models.IntegerField()),
                ('minimum_amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
